package MARC.myjavaproject;

import java.awt.Container;
import javax.swing.JPanel;
import MARC.RemoteHost.ClientMainWindoeForInitiating;
import MARC.RemoteHost.TrayIconWithPopForHost;
import MARC.Administrator.ServerMainWindoeForInitiating;
import MARC.Administrator.TrayIconWithPopForAdmin;
import MARC.myjavaproject.LogInfo.ForAdministrator.AppLogInfoForAdministrator;

/**
 *
 * @author PARTHO BISWAS
 */
public class OpeningWindow_Panel extends javax.swing.JPanel {

    private static OpeningWindow_frame OpWi_Fr = new OpeningWindow_frame();

    /** Creates new form OpeningWindow_Panel */
    public OpeningWindow_Panel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoiseLabel = new javax.swing.JLabel();
        StartAdmin = new javax.swing.JButton();
        StartHost = new javax.swing.JButton();
        StartBoth = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setOpaque(false);

        ChoiseLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 24));
        ChoiseLabel.setForeground(new java.awt.Color(51, 0, 204));
        ChoiseLabel.setText("Make only one choice...");

        StartAdmin.setBackground(new java.awt.Color(0, 0, 0));
        StartAdmin.setFont(new java.awt.Font("Monotype Corsiva", 3, 18));
        StartAdmin.setForeground(new java.awt.Color(102, 102, 102));
        StartAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MARC/myjavaproject/resources/kdm-config-icon.png"))); // NOI18N
        StartAdmin.setToolTipText("Start Admin");
        StartAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        StartAdmin.setIconTextGap(0);
        StartAdmin.setOpaque(false);
        StartAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAdminActionPerformed(evt);
            }
        });

        StartHost.setBackground(new java.awt.Color(0, 0, 0));
        StartHost.setFont(new java.awt.Font("Monotype Corsiva", 3, 18));
        StartHost.setForeground(new java.awt.Color(102, 102, 102));
        StartHost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MARC/myjavaproject/resources/krfb-icon.png"))); // NOI18N
        StartHost.setToolTipText("Start Host");
        StartHost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        StartHost.setOpaque(false);
        StartHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartHostActionPerformed(evt);
            }
        });

        StartBoth.setBackground(new java.awt.Color(0, 0, 0));
        StartBoth.setFont(new java.awt.Font("Monotype Corsiva", 3, 18));
        StartBoth.setForeground(new java.awt.Color(102, 102, 102));
        StartBoth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MARC/myjavaproject/resources/k-user-icon.png"))); // NOI18N
        StartBoth.setToolTipText("Start Both");
        StartBoth.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        StartBoth.setOpaque(false);
        StartBoth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBothActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Monotype Corsiva", 3, 18));
        Exit.setForeground(new java.awt.Color(102, 102, 102));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MARC/myjavaproject/resources/index48.png"))); // NOI18N
        Exit.setToolTipText("Exit");
        Exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        Exit.setOpaque(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChoiseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StartBoth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StartAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StartHost, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(ChoiseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartHost, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(StartAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartBoth, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StartAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAdminActionPerformed


        //        ServerMainWindoeForInitiating SMWFI = new ServerMainWindoeForInitiating();
        // this create's a tray icon and it's relevant popup menu
        TrayIconWithPopForAdmin.createAndShowGUIadd();
        //        SMWFI.setVisible( true ); // display frame
        ServerMainWindoeForInitiating.main(null);
//        ServerMainWindoeForInitiating.showServerMainWindoeForInitiating();
//        ServerMainWindoeForInitiating_Frame.main(null);

        this.close();    //closes this OpeningWindow
//        this.
//        new OpeningWindow_frame().setVisible(false);
//        OpeningWindow_frame.main(null);
//        OpeningWindow_frame.clo();
//        OpWi_F.getContentPane().setVisible(false);
//        Main.main(null).OpWi_Fr.setVisible(false);
//        this.exit();

//          this line shows log info on consone and adminLogInfoTextArea
            if(ServerMainWindoeForInitiating.isLogEnable == Boolean.TRUE)
            {
                AppLogInfoForAdministrator.logger.info("Administrator has been started");
            }


        
    }//GEN-LAST:event_StartAdminActionPerformed

    private void StartHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartHostActionPerformed

        //        ClientMainWindoeForInitiating CMWFI = new ClientMainWindoeForInitiating();
        // this create's a tray icon and it's relevant popup menu
//        ServerMainWindoeForInitiating.main(null);
        TrayIconWithPopForHost.createAndShowGUIadd();
        //        CMWFI.setVisible( true ); // display frame
        ClientMainWindoeForInitiating.main(null);


//        ServerMainWindoeForInitiating SMWFI03 = new ServerMainWindoeForInitiating();
        
//        ServerMainWindoeForInitiating.closeServerMainWindoeForInitiating();
//        ServerMainWindoeForInitiating.main(null);
//        ServerMainWindoeForInitiating.SMWFI02.dispose();
//        ServerMainWindoeForInitiating.closeServerMainWindoeForInitiating();

        this.close();


//           ServerMainWindoeForInitiating.main(null);


//           ServerMainWindoeForInitiating.closeServerMainWindoeForInitiating();

//          this line shows log info on consone and adminLogInfoTextArea
            if(ServerMainWindoeForInitiating.isLogEnable == Boolean.TRUE)
            {
                AppLogInfoForAdministrator.logger.info("Host has been started");
            }



    }//GEN-LAST:event_StartHostActionPerformed

    private void StartBothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBothActionPerformed

        //        ServerMainWindoeForInitiating SMWFI = new ServerMainWindoeForInitiating();
        // this create's a tray iconfor Admin Module and it's relevant popup menu
        TrayIconWithPopForAdmin.createAndShowGUIadd();
        //        SMWFI.setVisible( true ); // display frame
        ServerMainWindoeForInitiating.main(null);


        //        ClientMainWindoeForInitiating CMWFI = new ClientMainWindoeForInitiating();
        // this create's a tray icon and it's relevant popup menu
        TrayIconWithPopForHost.createAndShowGUIadd();
        //        CMWFI.setVisible( true ); // display frame
        ClientMainWindoeForInitiating.main(null);



        main.iti ++;
        this.close();     //closes this OpeningWindow
        
//          this line shows log info on consone and adminLogInfoTextArea
            if(ServerMainWindoeForInitiating.isLogEnable == Boolean.TRUE)
            {
                AppLogInfoForAdministrator.logger.info("Administrator & Host has been started");
            }



    }//GEN-LAST:event_StartBothActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

//          this line shows log info on consone and adminLogInfoTextArea
            if(ServerMainWindoeForInitiating.isLogEnable == Boolean.TRUE)
            {
                AppLogInfoForAdministrator.logger.info("Application exirs");
            }



        System.exit(0);

    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoiseLabel;
    private javax.swing.JButton Exit;
    private javax.swing.JButton StartAdmin;
    private javax.swing.JButton StartBoth;
    private javax.swing.JButton StartHost;
    // End of variables declaration//GEN-END:variables

    public void close()
    {
//        this.setVisible(false);
        this.getTopLevelAncestor().setVisible(false);   
//        jp.setVisible(false);
//        this.getRootPane().setVisible(false);
//        this.getRootPane().getContentPane().setVisible(false);
    }


}
