package MARC.Administrator;


import java.awt.Toolkit;
import MARC.RemoteHost.HostProperties;
import MARC.myjavaproject.Server.RMI.ServerAdmin;
import MARC.Administrator.ServerMainWindoeForInitiating;
import MARC.myjavaproject.LogInfo.ForAdministrator.AppLogInfoForAdministrator;
import MARC.myjavaproject.Viewer.RMI.Viewer;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class AddNewPcGUI extends javax.swing.JFrame {


    public static  int j=0;
    

//    public static String host_os_na;

    /** Creates new form AddNewPcGUI */
    public AddNewPcGUI() {
        initComponents();
        setLocationRelativeTo( null );
        setIconImage(Toolkit.getDefaultToolkit().getImage("resourse/kdm-config-icon.png"));


        HostConfigForAddingPc.loadConfiguration();

        jTextFieldIPAdr.setText(HostConfigForAddingPc.server_address);
        jTextFieldPort.setText(String.valueOf(HostConfigForAddingPc.server_port));
        jTextFieldUsername.setText(HostConfigForAddingPc.username);
        jPasswordField.setText(HostConfigForAddingPc.password);
        jCheckBoxSSLEnabled.setSelected(HostConfigForAddingPc.ssl_enabled);



//        host_os_na = HostProperties.host_os_name;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPcMomPanel = new javax.swing.JPanel();
        addPaTabbedPane = new javax.swing.JTabbedPane();
        addressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIPAdr = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        othersPanel = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jCheckBoxSSLEnabled = new javax.swing.JCheckBox();
        okPanel = new javax.swing.JPanel();
        addPcOKButton = new javax.swing.JButton();
        addPcCanButton = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setTitle("Add New PC");
        setIconImages(null);
        setResizable(false);

        addPcMomPanel.setBackground(new java.awt.Color(102, 102, 102));
        addPcMomPanel.setForeground(new java.awt.Color(153, 0, 0));

        addPaTabbedPane.setBackground(new java.awt.Color(51, 51, 51));
        addPaTabbedPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        addPaTabbedPane.setForeground(new java.awt.Color(153, 0, 51));

        addressPanel.setBackground(new java.awt.Color(48, 73, 91));
        addressPanel.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setText("Host Address:");

        jLabel2.setText("Host Port:");

        jTextFieldIPAdr.setText("127.0.0.1");
        jTextFieldIPAdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPAdrActionPerformed(evt);
            }
        });

        jTextFieldPort.setText("6666");

        jLabel5.setText("Address book name:");

        jTextFieldName.setText("PC - " + j);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldIPAdr, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIPAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        addPaTabbedPane.addTab("Address", addressPanel);

        othersPanel.setBackground(new java.awt.Color(46, 83, 84));
        othersPanel.setForeground(new java.awt.Color(153, 0, 0));

        jTextFieldUsername.setText("admin");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        jPasswordField.setText("admin");

        jCheckBoxSSLEnabled.setText("Secured connection (SSL)");
        jCheckBoxSSLEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSSLEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(othersPanelLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(othersPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                        .addComponent(jCheckBoxSSLEnabled))
                    .addGap(84, 84, 84)))
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(othersPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBoxSSLEnabled)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        addPaTabbedPane.addTab("Acc info", othersPanel);

        okPanel.setBackground(new java.awt.Color(51, 51, 51));
        okPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        okPanel.setForeground(new java.awt.Color(153, 0, 0));

        addPcOKButton.setBackground(new java.awt.Color(102, 102, 102));
        addPcOKButton.setForeground(new java.awt.Color(153, 0, 0));
        addPcOKButton.setText("OK");
        addPcOKButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addPcOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPcOKButtonActionPerformed(evt);
            }
        });

        addPcCanButton.setBackground(new java.awt.Color(102, 102, 102));
        addPcCanButton.setForeground(new java.awt.Color(153, 0, 0));
        addPcCanButton.setText("CANCLE");
        addPcCanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPcCanButtonActionPerformed(evt);
            }
        });

        helpLabel.setBackground(new java.awt.Color(102, 102, 102));
        helpLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        helpLabel.setForeground(new java.awt.Color(204, 204, 204));
        helpLabel.setText("Help");
        helpLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));

        javax.swing.GroupLayout okPanelLayout = new javax.swing.GroupLayout(okPanel);
        okPanel.setLayout(okPanelLayout);
        okPanelLayout.setHorizontalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(addPcOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addPcCanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        okPanelLayout.setVerticalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPcOKButton)
                    .addComponent(addPcCanButton)
                    .addComponent(helpLabel))
                .addContainerGap())
        );

        jTextPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Kristen ITC", 2, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(204, 0, 0));
        jTextPane1.setText("Enter the value of the relative fields for hose PC, which you want to control from here. These information must be matched with the Host PC.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout addPcMomPanelLayout = new javax.swing.GroupLayout(addPcMomPanel);
        addPcMomPanel.setLayout(addPcMomPanelLayout);
        addPcMomPanelLayout.setHorizontalGroup(
            addPcMomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPcMomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPcMomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(addPaTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(okPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        addPcMomPanelLayout.setVerticalGroup(
            addPcMomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPcMomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPaTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPcMomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPcMomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addPcOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPcOKButtonActionPerformed

     for(int i=0;i<=ServerMainWindoeForInitiating.tableDispIndex;i++)
     {
        if( ServerMainWindoeForInitiating.directAccTable1.getValueAt(i, 1).equals( jTextFieldIPAdr.getText() ) )
        {
            JOptionPane.showMessageDialog(this, "This PC already exist in the table ! !! !!!" + "\n" + "Retype IP address. .. ...", "ERROR", JOptionPane.ERROR_MESSAGE);        
            return;
        }
     }



     dispose();
     ServerMainWindoeForInitiating.startViewer(jTextFieldIPAdr.getText(),
             Integer.parseInt(jTextFieldPort.getText()),
             jTextFieldUsername.getText(),
             String.copyValueOf(jPasswordField.getPassword()),
             jCheckBoxSSLEnabled.isSelected());

//          this line shows log info on consone and adminLogInfoTextArea
     if(ServerMainWindoeForInitiating.isLogEnable == Boolean.TRUE)
     {
             AppLogInfoForAdministrator.logger.info("A New PC is trying to get connected");
     }

    }//GEN-LAST:event_addPcOKButtonActionPerformed

    private void jCheckBoxSSLEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSSLEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSSLEnabledActionPerformed

    private void addPcCanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPcCanButtonActionPerformed
        dispose();
    }//GEN-LAST:event_addPcCanButtonActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldIPAdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPAdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPAdrActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                j++;
                new AddNewPcGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane addPaTabbedPane;
    private javax.swing.JButton addPcCanButton;
    private javax.swing.JPanel addPcMomPanel;
    private javax.swing.JButton addPcOKButton;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JLabel helpLabel;
    public static javax.swing.JCheckBox jCheckBoxSSLEnabled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextFieldIPAdr;
    public static javax.swing.JTextField jTextFieldName;
    public static javax.swing.JTextField jTextFieldPort;
    public static javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel okPanel;
    private javax.swing.JPanel othersPanel;
    // End of variables declaration//GEN-END:variables

}
